const milkProducts = [
  { name: "Cilonmum Colos Baby 24h", status: "Giả", company: "Công ty TNHH Sữa Giả" },
  { name: "Cilonmum Colos Pedia 24h", status: "Giả", company: "Công ty TNHH Sữa Giả" },
  { name: "Cilonmum For Mum Colostrum 24h", status: "Giả", company: "Công ty TNHH Sữa Giả" },
  { name: "Cilonmum Gludiabet Colostrum 24h", status: "Giả", company: "Công ty TNHH Sữa Giả" },
  { name: "Cilonmum Kid Goat Colostrum 24h", status: "Giả", company: "Công ty TNHH Sữa Giả" },
  { name: "Cilonmum Pedia Goat Colostrum 24h", status: "Giả", company: "Công ty TNHH Sữa Giả" },
  { name: "Cilonmum Diasure Colostrum 24h", status: "Giả", company: "Công ty TNHH Sữa Giả" },
  { name: "Talacmum For Mum", status: "Giả", company: "Công ty TNHH Sữa Giả" },
  { name: "Talacmum Gain", status: "Giả", company: "Công ty TNHH Sữa Giả" },
  { name: "Talacmum Gludiabet", status: "Giả", company: "Công ty TNHH Sữa Giả" },
  { name: "Talacmum Goat Kids", status: "Giả", company: "Công ty TNHH Sữa Giả" },
  { name: "Talacmum Goat Pedia", status: "Giả", company: "Công ty TNHH Sữa Giả" },
  { name: "Talacmum IQ Grow", status: "Đang điều tra", company: "Công ty TNHH Sữa Nghi Vấn" },
  { name: "Talacmum Kalosure Gold", status: "Đang điều tra", company: "Công ty TNHH Sữa Nghi Vấn" },
  { name: "Talacmum Kid Baby", status: "Đang điều tra", company: "Công ty TNHH Sữa Nghi Vấn" },
  { name: "Talacmum Pedia Cool", status: "Đang điều tra", company: "Công ty TNHH Sữa Nghi Vấn" },
  { name: "Colos 24h Premium Kid Baby", status: "Đang điều tra", company: "Công ty TNHH Sữa Nghi Vấn" },
  { name: "Colos 24h Premium", status: "Đang điều tra", company: "Công ty TNHH Sữa Nghi Vấn" },
  { name: "NewSure Colos 24h Kid Plus", status: "Đang điều tra", company: "Công ty TNHH Sữa Nghi Vấn" },
  { name: "Baby Care Colostrum Kid", status: "Đang điều tra", company: "Công ty TNHH Sữa Nghi Vấn" },
  { name: "Bold Milk For Mum Colostrum", status: "Đang điều tra", company: "Công ty TNHH Sữa Nghi Vấn" },
  { name: "Bold Milk Glu Sure Colostrum", status: "Đang điều tra", company: "Công ty TNHH Sữa Nghi Vấn" },
  { name: "Sure IQ Sure Gold", status: "Đang điều tra", company: "Công ty TNHH Sữa Nghi Vấn" },
  { name: "Nance Colostrum 24h Kid", status: "Đang điều tra", company: "Công ty TNHH Sữa Nghi Vấn" },
  { name: "Nance Goat Pedia", status: "Đang điều tra", company: "Công ty TNHH Sữa Nghi Vấn" },
  { name: "Cilonmum Mama", status: "Đang điều tra", company: "Công ty TNHH Sữa Nghi Vấn" },
  { name: "Cilonmum Colos Gain 24H 3", status: "Đang điều tra", company: "Công ty TNHH Sữa Nghi Vấn" },
  { name: "Cilonmum Canxi Colostrum 24H", status: "Đang điều tra", company: "Công ty TNHH Sữa Nghi Vấn" },
  { name: "Newsure Colos 24H Grow IQ Plus", status: "Đang điều tra", company: "Công ty TNHH Sữa Nghi Vấn" },
  { name: "Newsure Colos 24H Pedia Goat", status: "Đang điều tra", company: "Công ty TNHH Sữa Nghi Vấn" },
  { name: "Baby Care Colostrum Pedia 2", status: "Đang điều tra", company: "Công ty TNHH Sữa Nghi Vấn" },
  { name: "SureIQ Gludiabet", status: "Đang điều tra", company: "Công ty TNHH Sữa Nghi Vấn" },
  { name: "Kenmil Sure Gold", status: "Đang điều tra", company: "Công ty TNHH Sữa Nghi Vấn" },
  { name: "Kenmil Premium Grow - Weight", status: "Đang điều tra", company: "Công ty TNHH Sữa Nghi Vấn" },
  { name: "Kenmil Premium Kid Goat", status: "Đang điều tra", company: "Công ty TNHH Sữa Nghi Vấn" },
  { name: "Kodo A+ Digest Colostrum 2", status: "Đang điều tra", company: "Công ty TNHH Sữa Nghi Vấn" },
  { name: "Kodo A+ EPA PRO", status: "Đang điều tra", company: "Công ty TNHH Sữa Nghi Vấn" },
  { name: "Hikidme Colos 24H IQ Grow", status: "Đang điều tra", company: "Công ty TNHH Sữa Nghi Vấn" },
  { name: "Hikidme Colos 24H Pedia", status: "Đang điều tra", company: "Công ty TNHH Sữa Nghi Vấn" },
  { name: "Hikidme Colos 24H Baby", status: "Đang điều tra", company: "Công ty TNHH Sữa Nghi Vấn" },
  { name: "Hikidme Colos 24H Gain", status: "Đang điều tra", company: "Công ty TNHH Sữa Nghi Vấn" },
  { name: "Bonlac+ Infant O+", status: "Đang điều tra", company: "Công ty TNHH Sữa Nghi Vấn" },
  { name: "Bonlac+ Luxury Goat Bio - IQ Cool", status: "Đang điều tra", company: "Công ty TNHH Sữa Nghi Vấn" },
  { name: "Bonlac+ Luxury Colos 24H Kid", status: "Đang điều tra", company: "Công ty TNHH Sữa Nghi Vấn" },
  { name: "Bonlac+ Luxury Colos 24H", status: "Đang điều tra", company: "Công ty TNHH Sữa Nghi Vấn" },
  { name: "Hito Grow", status: "Đang điều tra", company: "Công ty TNHH Sữa Nghi Vấn" },
  { name: "HDO Diabetes", status: "Đang điều tra", company: "Công ty TNHH Sữa Nghi Vấn" },
  { name: "HDO Canxi Nano", status: "Đang điều tra", company: "Công ty TNHH Sữa Nghi Vấn" },
  { name: "HDO Grow IQ", status: "Đang điều tra", company: "Công ty TNHH Sữa Nghi Vấn" },
  { name: "HDO Pedia Plus", status: "Đang điều tra", company: "Công ty TNHH Sữa Nghi Vấn" },
  { name: "HDO Sure Gold", status: "Đang điều tra", company: "Công ty TNHH Sữa Nghi Vấn" },
  { name: "Celac Gain Biomin 2+", status: "Đang điều tra", company: "Công ty TNHH Sữa Nghi Vấn" }
];